// export interface IAddress {
//     area: string,
//     road: string
// }

export interface Person {
  givenName: string;
  surName: string;
  age: number;
  email: string;
  address: string; //IAddress
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  address: string;
}

export const ManyPerson: EPerson[] = [
  {
    givenName: 'Adam',
    surName: 'Baker',
    email: 'a.c@gmail.com',
    age: '73',
    address: 'Crystal',
  },
  {
    givenName: 'Victoria',
    surName: 'Hall',
    email: 'vmhall77@aol.com',
    age: '40',
    address: 'Woodman',
  },
  {
    givenName: 'Alexis',
    surName: 'Davis',
    email: 'alexisdavis@live.com',
    age: '57',
    address: 'Bryants Store',
  },
  {
    givenName: 'Anthony',
    surName: 'James',
    email: 'anthony.james@outlook.com',
    age: '52',
    address: 'Dalton',
  },
  {
    givenName: 'Steven',
    surName: 'Alexander',
    email: 's_alexander53@live.com',
    age: '27',
    address: 'Hamilton',
  },
  {
    givenName: 'Steven',
    surName: 'Russell',
    email: 's.russell@ymail.com',
    age: '77',
    address: 'Capulin',
  },
  {
    givenName: 'Amelia',
    surName: 'Henderson',
    email: 'ajhenderson@ymail.com',
    age: '54',
    address: 'New Orleans',
  },
  {
    givenName: 'John',
    surName: 'Peterson',
    email: 'johnray53@yahoo.com',
    age: '49',
    address: 'Harkers Island',
  },
  {
    givenName: 'Layla',
    surName: 'Butler',
    email: 'laylamichellebutler@hotmail.com',
    age: '39',
    address: 'Westborough',
  },
  {
    givenName: 'Victoria',
    surName: 'Evans',
    email: 'victoriaevans@rocketmail.com',
    age: '72',
    address: 'Lanse',
  },
  {
    givenName: 'Amanda',
    surName: 'Peterson',
    email: 'amanda@hotmail.com',
    age: '19',
    address: 'Mount Vernon',
  },
  {
    givenName: 'Heather',
    surName: 'White',
    email: 'h.l.white@aol.com',
    age: '48',
    address: 'Peoria',
  },
  {
    givenName: 'Samantha',
    surName: 'Carter',
    email: 'samantha_carter@yahoo.com',
    age: '63',
    address: 'Bloomington',
  },
  {
    givenName: 'Victoria',
    surName: 'Washington',
    email: 'victoria_washington@outlook.com',
    age: '36',
    address: 'Kirkwood',
  },
  {
    givenName: 'Charles',
    surName: 'Rogers',
    email: 'charles_rogers@yahoo.com',
    age: '47',
    address: 'Lakeport',
  },
  {
    givenName: 'Sofia',
    surName: 'Thompson',
    email: 's.thompson@yahoo.com',
    age: '39',
    address: 'Dallas',
  },
  {
    givenName: 'Joshua',
    surName: 'Rodriguez',
    email: 'joshuajrodriguez@hotmail.com',
    age: '37',
    address: 'Betterton',
  },
  {
    givenName: 'Ashley',
    surName: 'King',
    email: 'a.king49@gmail.com',
    age: '55',
    address: 'Doucette',
  },
  {
    givenName: 'Jose',
    surName: 'Long',
    email: 'j_r_long@hotmail.com',
    age: '21',
    address: 'Sandy Hook',
  },
  {
    givenName: 'Eric',
    surName: 'Patterson',
    email: 'e.h.patterson@live.com',
    age: '51',
    address: 'Cutten',
  },
  {
    givenName: 'Charlotte',
    surName: 'Ward',
    email: 'charlotte32@ymail.com',
    age: '64',
    address: 'Montgomery',
  },
  {
    givenName: 'Ashley',
    surName: 'Cook',
    email: 'arcook47@yahoo.com',
    age: '77',
    address: 'Hartford',
  },
  {
    givenName: 'Theodore',
    surName: 'Lewis',
    email: 'talewis@outlook.com',
    age: '49',
    address: 'Hillburn',
  },
  {
    givenName: 'Grace',
    surName: 'Simmons',
    email: 'grace.r@yahoo.com',
    age: '23',
    address: 'Indianapolis',
  },
  {
    givenName: 'Charles',
    surName: 'Coleman',
    email: 'charlescoleman@gmail.com',
    age: '34',
    address: 'Nashville',
  },
  {
    givenName: 'William',
    surName: 'Moore',
    email: 'w.r.moore@aol.com',
    age: '58',
    address: 'Antler',
  },
  {
    givenName: 'Ava',
    surName: 'Mitchell',
    email: 'ava_m_mitchell@aol.com',
    age: '43',
    address: 'Indianapolis',
  },
  {
    givenName: 'Kaitlyn',
    surName: 'Taylor',
    email: 'kaitlyn_mae@yahoo.com',
    age: '36',
    address: 'New Castle',
  },
  {
    givenName: 'Hannah',
    surName: 'Perez',
    email: 'h_j_perez@hotmail.com',
    age: '73',
    address: 'Gadsden',
  },
  {
    givenName: 'Aubrey',
    surName: 'Garcia',
    email: 'a_garcia@yahoo.com',
    age: '55',
    address: 'Akron',
  },
  {
    givenName: 'Tiffany',
    surName: 'Torres',
    email: 'tiffany.torres@live.com',
    age: '18',
    address: 'Des Moines',
  },
  {
    givenName: 'Stephen',
    surName: 'Green',
    email: 'stephengreen@hotmail.com',
    age: '76',
    address: 'Long Beach',
  },
  {
    givenName: 'Sebastian',
    surName: 'Thompson',
    email: 'sebastianthompson@gmail.com',
    age: '75',
    address: 'Cornwall On Hudson',
  },
  {
    givenName: 'Matthew',
    surName: 'Long',
    email: 'mglong@yahoo.com',
    age: '50',
    address: 'Cairo',
  },
  {
    givenName: 'Jessica',
    surName: 'White',
    email: 'jessica_white@outlook.com',
    age: '36',
    address: 'Mi Wuk Village',
  },
  {
    givenName: 'Jennifer',
    surName: 'Bennett',
    email: 'jennifer@gmail.com',
    age: '39',
    address: 'Rancocas',
  },
  {
    givenName: 'Adam',
    surName: 'Martin',
    email: 'adam_martin@rocketmail.com',
    age: '43',
    address: 'Lafayette',
  },
  {
    givenName: 'Anthony',
    surName: 'Murphy',
    email: 'anthony_murphy@gmail.com',
    age: '24',
    address: 'Shreveport',
  },
  {
    givenName: 'Kyle',
    surName: 'Washington',
    email: 'k.washington87@hotmail.com',
    age: '47',
    address: 'Denver',
  },
  {
    givenName: 'Danielle',
    surName: 'Gray',
    email: 'dgray@live.com',
    age: '33',
    address: 'Long Creek',
  },
  {
    givenName: 'Audrey',
    surName: 'Richardson',
    email: 'a.richardson@live.com',
    age: '77',
    address: 'Monroe',
  },
  {
    givenName: 'Abigail',
    surName: 'King',
    email: 'a_king26@ymail.com',
    age: '73',
    address: 'Thompsontown',
  },
  {
    givenName: 'Audrey',
    surName: 'Bennett',
    email: 'a_bennett@gmail.com',
    age: '44',
    address: 'Spofford',
  },
  {
    givenName: 'Ava',
    surName: 'Smith',
    email: 'asmith@live.com',
    age: '21',
    address: 'Oil address',
  },
  {
    givenName: 'Zachary',
    surName: 'Diaz',
    email: 'z.w@hotmail.com',
    age: '43',
    address: 'Rock address Falls',
  },
  {
    givenName: 'Mark',
    surName: 'Cook',
    email: 'markalexandercook@aol.com',
    age: '45',
    address: 'Kansas address',
  },
  {
    givenName: 'Mateo',
    surName: 'Taylor',
    email: 'mateowayne@hotmail.com',
    age: '40',
    address: 'Peru',
  },
  {
    givenName: 'Courtney',
    surName: 'Hughes',
    email: 'courtney.hughes@yahoo.com',
    age: '45',
    address: 'Peoria',
  },
  {
    givenName: 'Mark',
    surName: 'Garcia',
    email: 'mtgarcia@gmail.com',
    age: '76',
    address: 'Nashville',
  },
  {
    givenName: 'James',
    surName: 'Alexander',
    email: 'james_alexander@live.com',
    age: '77',
    address: 'Howard Beach',
  },
  {
    givenName: 'Laura',
    surName: 'Adams',
    email: 'laura.r.adams@outlook.com',
    age: '68',
    address: 'Bristol',
  },
  {
    givenName: 'Jose',
    surName: 'Davis',
    email: 'j.davis61@yahoo.com',
    age: '20',
    address: 'Dallas',
  },
  {
    givenName: 'Aubrey',
    surName: 'Jones',
    email: 'aubreyann@outlook.com',
    age: '23',
    address: 'Rosendale',
  },
  {
    givenName: 'Erin',
    surName: 'Williams',
    email: 'erin_faith_williams@yahoo.com',
    age: '36',
    address: 'Rochester',
  },
  {
    givenName: 'Anna',
    surName: 'Robinson',
    email: 'anna.l.robinson@aol.com',
    age: '38',
    address: 'Acton',
  },
  {
    givenName: 'Heather',
    surName: 'Diaz',
    email: 'heather.ann.diaz@rocketmail.com',
    age: '65',
    address: 'Springfield',
  },
  {
    givenName: 'Jennifer',
    surName: 'Griffin',
    email: 'jennifer_griffin@live.com',
    age: '57',
    address: 'Eugene',
  },
  {
    givenName: 'Jasmine',
    surName: 'Barnes',
    email: 'j_barnes@gmail.com',
    age: '72',
    address: 'Richmond',
  },
  {
    givenName: 'Timothy',
    surName: 'Griffin',
    email: 'timothy_r_griffin21@aol.com',
    age: '46',
    address: 'Roland',
  },
  {
    givenName: 'Katherine',
    surName: 'Brooks',
    email: 'katherine.renee.brooks@aol.com',
    age: '31',
    address: 'Buffalo',
  },
  {
    givenName: 'Erin',
    surName: 'Murphy',
    email: 'erin_murphy24@aol.com',
    age: '24',
    address: 'Scotland',
  },
  {
    givenName: 'David',
    surName: 'Brown',
    email: 'david.henry.brown@outlook.com',
    age: '68',
    address: 'Rehobeth',
  },
  {
    givenName: 'Chelsea',
    surName: 'Kelly',
    email: 'chelsea.kelly@rocketmail.com',
    age: '29',
    address: 'Bendersville',
  },
  {
    givenName: 'Gabriel',
    surName: 'Foster',
    email: 'g.foster@rocketmail.com',
    age: '64',
    address: 'Elmsford',
  },
  {
    givenName: 'Kaitlyn',
    surName: 'Anderson',
    email: 'kaitlyn.mary.anderson64@aol.com',
    age: '59',
    address: 'Pembroke Pines',
  },
  {
    givenName: 'Jasmine',
    surName: 'Powell',
    email: 'jasmine.rose.powell@gmail.com',
    age: '54',
    address: 'Madison',
  },
  {
    givenName: 'Victoria',
    surName: 'Lopez',
    email: 'victoria_rose_lopez59@aol.com',
    age: '65',
    address: 'Belvidere',
  },
  {
    givenName: 'Joseph',
    surName: 'Thompson',
    email: 'josephfthompson@live.com',
    age: '39',
    address: 'Savannah',
  },
  {
    givenName: 'Alexander',
    surName: 'Evans',
    email: 'alexander.evans@gmail.com',
    age: '59',
    address: 'Independence',
  },
  {
    givenName: 'Christina',
    surName: 'Ross',
    email: 'christinadawnross@yahoo.com',
    age: '29',
    address: 'Plains',
  },
  {
    givenName: 'Jose',
    surName: 'Phillips',
    email: 'j_phillips@ymail.com',
    age: '22',
    address: 'Crestview',
  },
  {
    givenName: 'Adam',
    surName: 'Wood',
    email: 'adam.james@gmail.com',
    age: '20',
    address: 'Lone Tree',
  },
  {
    givenName: 'Kevin',
    surName: 'Bell',
    email: 'kevinbell22@aol.com',
    age: '40',
    address: 'Gwynneville',
  },
  {
    givenName: 'Ethan',
    surName: 'Kelly',
    email: 'ethanmkelly@rocketmail.com',
    age: '50',
    address: 'Three Oaks',
  },
  {
    givenName: 'Joseph',
    surName: 'Murphy',
    email: 'joseph.lee.murphy@yahoo.com',
    age: '75',
    address: 'Kansas address',
  },
  {
    givenName: 'Claire',
    surName: 'Rogers',
    email: 'c_rogers@ymail.com',
    age: '53',
    address: 'Perkinston',
  },
  {
    givenName: 'Sophia',
    surName: 'Ross',
    email: 'sophia_r_ross@ymail.com',
    age: '43',
    address: 'Fort Worth',
  },
  {
    givenName: 'Kyle',
    surName: 'Ward',
    email: 'k.w.ward@outlook.com',
    age: '18',
    address: 'Raleigh',
  },
  {
    givenName: 'Emily',
    surName: 'Watson',
    email: 'emilymae@outlook.com',
    age: '29',
    address: 'Charlottesville',
  },
  {
    givenName: 'Michael',
    surName: 'Johnson',
    email: 'mrjohnson@aol.com',
    age: '25',
    address: 'Curtice',
  },
  {
    givenName: 'Jessica',
    surName: 'Thomas',
    email: 'jessica_jane_thomas@yahoo.com',
    age: '60',
    address: 'Sandy Lake',
  },
  {
    givenName: 'Sara',
    surName: 'Turner',
    email: 'sara_turner@hotmail.com',
    age: '64',
    address: 'Greeley',
  },
  {
    givenName: 'Audrey',
    surName: 'Roberts',
    email: 'amroberts91@hotmail.com',
    age: '21',
    address: 'Geneva',
  },
  {
    givenName: 'Aiden',
    surName: 'Ward',
    email: 'aiden_charles_ward@yahoo.com',
    age: '69',
    address: 'Mauckport',
  },
  {
    givenName: 'Grace',
    surName: 'Edwards',
    email: 'grace_michelle_edwards84@gmail.com',
    age: '20',
    address: 'Salt Lake address',
  },
  {
    givenName: 'Julian',
    surName: 'Powell',
    email: 'julian_thomas_powell@aol.com',
    age: '56',
    address: 'Canon address',
  },
  {
    givenName: 'Samuel',
    surName: 'Jones',
    email: 'samuel.wayne.jones@aol.com',
    age: '62',
    address: 'Pittsburgh',
  },
  {
    givenName: 'Alexandra',
    surName: 'Morgan',
    email: 'alexandra.morgan@ymail.com',
    age: '70',
    address: 'Peotone',
  },
  {
    givenName: 'Dylan',
    surName: 'Jones',
    email: 'dylan_jones@gmail.com',
    age: '40',
    address: 'Goodman',
  },
  {
    givenName: 'Thomas',
    surName: 'Jones',
    email: 'thomas_d_jones@gmail.com',
    age: '49',
    address: 'Cynthiana',
  },
  {
    givenName: 'Nicole',
    surName: 'Foster',
    email: 'nicolemargaretfoster3@live.com',
    age: '28',
    address: 'Matagorda',
  },
  {
    givenName: 'Benjamin',
    surName: 'Price',
    email: 'benjamin.r.price@hotmail.com',
    age: '61',
    address: 'Emeryville',
  },
  {
    givenName: 'Megan',
    surName: 'Phillips',
    email: 'mphillips47@ymail.com',
    age: '68',
    address: 'Washington',
  },
  {
    givenName: 'Isaac',
    surName: 'Clark',
    email: 'i.r.clark81@aol.com',
    age: '53',
    address: 'Columbus',
  },
  {
    givenName: 'Jennifer',
    surName: 'Powell',
    email: 'jennifer_m@ymail.com',
    age: '72',
    address: 'Yonkers',
  },
  {
    givenName: 'Kaitlyn',
    surName: 'Miller',
    email: 'k_miller@rocketmail.com',
    age: '27',
    address: 'Tuleta',
  },
  {
    givenName: 'Maria',
    surName: 'Ramirez',
    email: 'mariaeramirez@ymail.com',
    age: '42',
    address: 'Warrensburg',
  },
  {
    givenName: 'Lillian',
    surName: 'Cook',
    email: 'lillian_dawn_cook@ymail.com',
    age: '55',
    address: 'Burnettsville',
  },
  {
    givenName: 'Joseph',
    surName: 'Diaz',
    email: 'joseph_diaz@ymail.com',
    age: '42',
    address: 'Damascus',
  },
  {
    givenName: 'Elizabeth',
    surName: 'Adams',
    email: 'elizabeth_r_adams@outlook.com',
    age: '54',
    address: 'Hillsdale',
  },
];
